name: Setup Node.js and pnpm
description: Set up Node.js and pnpm environment

inputs:
  node-version:
    description: "Node.js version to install"
    required: true
    default: "14.x"
  pnpm-version:
    description: "pnpm version to install"
    required: true
    default: "latest"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

    - uses: actions/cache@v2
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      run: |
        npm install -g pnpm@${{ inputs.pnpm-version }}

    - name: Install dependencies
      run: pnpm install
